version: 2.1

orbs:
  android: circleci/android@2.1.2
  gradle: circleci/gradle@3.0.0
  
jobs:
  build:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/run-tests:
          test-command: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - run:
          name: save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  build-and-test:
    jobs:
      - build