version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  lint:
    executor:
      name: android/android-docker
      resource-class: xlarge
      tag: 2023.05.01
    steps:
      - checkout
      - android/restore-gradle-cache
      - run ./gradlew lintDebug
      - android/save-gradle-cache
  unit-test:
    executor:
      name: android/android-docker
      resource-class: xlarge
      tag: 2023.05.01
    steps:
      - checkout
      - android/restore-gradle-cache
      - run ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - store_test_results:
          path: ./app/build/test-results/testDebugUnitTest

workflows:
  main:
    jobs:
      - lint
      - unit-test