version: 2.1

orbs:
  android: circleci/android@2.3.0
  gradle: circleci/gradle@3.0.0

jobs:
  build:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - android/restore-gradle-cache
      - run:
          name: Chmod permissions # permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - android/run-tests:
          test-command: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - run:
          name: save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  build-and-test:
    jobs:
      - build