# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  unit-test:
    executor:
      name: android/android-docker
      tag: 2022.08.01
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - run:
          name: Save test results
          command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/build/test-result/.*xml" -exec cp {} ~/test-results/junit/ \:
          when: always
      - store-test-results:
          path: ~/test-results
      - store-artifacts:
          path: ~/test-results/junit
workflows:
  test-and-build:
    jobs:
      - unit-test